image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-activity-microservice:
  stage: build
  script:
    gradle boat-microservice:assemble boat-microservice:testClasses

checkStyle-activity-microservice:
  stage: staticAnalysis
  script:
    gradle boat-microservice:checkstyleMain boat-microservice:checkStyleTest
  allow_failure: true


PMD-activity-microservice:
  stage: staticAnalysis
  script:
    gradle boat-microservice:pmdMain
  allow_failure: true

test-activity-microservice:
  stage: test
  script:
    - gradle boat-microservice:test boat-microservice:jacocoTestReport
    - cat boat-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
